words = {
    "aardvark": "A burrowing nocturnal mammal that eats ants and termites.",
    "alligator": "A large semiaquatic reptile with a broad snout.",
    "alpaca": "A domesticated South American mammal valued for its fluffy wool.",
    "ant": "A small, industrious social insect that lives in colonies.",
    "anteater": "A mammal with a long snout and sticky tongue specialized for eating insects.",
    "antelope": "A swift, slender-horned ruminant mammal native to Africa and Eurasia.",
    "ape": "A tailess primate such as a chimpanzee, gorilla, or orangutan.",
    "armadillo": "A nocturnal mammal covered in bony plates.",
    "baboon": "A large Old World monkey with a dog-like snout.",
    "badger": "A stout-bodied burrowing nocturnal mammal of the weasel family.",
    "bat": "A nocturnal flying mammal that uses echolocation.",
    "bear": "A large, heavy-set carnivorous or omnivorous mammal with thick fur.",
    "beaver": "A semiaquatic rodent famous for building wooden dams and lodges.",
    "bee": "A flying insect known for pollination and making honey.",
    "bison": "A massive, shaggy-haired wild ox native to North America and Europe.",
    "boar": "A wild, tusked relative of the domestic pig.",
    "buffalo": "A large bovine animal with heavy horns.",
    "butterfly": "An insect with large, often brightly colored wings.",
    "camel": "A desert-dwelling mammal known for storing fat in its humps.",
    "capybara": "The largest living rodent in the world, native to South America.",
    "caribou": "A large North American reindeer.",
    "cat": "A small domesticated carnivorous feline popular as a pet.",
    "caterpillar": "The larval, worm-like stage of a butterfly or moth.",
    "cattle": "Large domesticated farm animals raised for meat or milk.",
    "chamois": "A goat-like antelope native to the mountains of Europe.",
    "cheetah": "The world's fastest land mammal, known for its spotted coat.",
    "chicken": "A common domesticated fowl raised for eggs and meat.",
    "chimpanzee": "A highly intelligent social primate closely related to humans.",
    "chinchilla": "A small, fluffy South American rodent prized for its soft fur.",
    "chough": "A noisy, black-feathered bird of the crow family with a red bill.",
    "clam": "A bivalve mollusk that burrows in sand or mud.",
    "cobra": "A venomous snake known for expanding its hood when threatened.",
    "cockroach": "A hardy, fast-running pest insect.",
    "cod": "A cold-water marine food fish.",
    "coyote": "A clever, howling wild canine native to North America.",
    "crab": "A crustacean with a flat shell and clawed front legs.",
    "crane": "A tall wading bird with a long neck and legs.",
    "crocodile": "A large, aggressive semiaquatic predatory reptile with a V-shaped snout.",
    "crow": "A clever, highly adaptable black bird known for problem-solving.",
    "curlew": "A wading bird with a long, downward-curved bill.",
    "deer": "A hoofed grazing animal where males typically grow antlers.",
    "dinosaur": "A massive extinct reptile that roamed prehistoric Earth.",
    "dog": "Man's best friend; a domesticated canine.",
    "dogfish": "A small species of shark.",
    "dolphin": "A highly intelligent, social marine mammal known for acrobatics.",
    "donkey": "A domesticated member of the horse family with long ears.",
    "dormouse": "A small, sleepy rodent known for long hibernation periods.",
    "dotterel": "A small, confiding plover bird of arctic and alpine regions.",
    "dove": "A plump-breasted bird often symbolizing peace.",
    "dragonfly": "An agile predatory insect with large eyes and transparent wings.",
    "duck": "A common aquatic web-footed bird.",
    "dugong": "A large marine mammal related to the manatee that grazes on seagrass.",
    "dunlin": "A small sandpiper bird that scurries along coastlines.",
    "eagle": "A majestic bird of prey with sharp vision and strong talons.",
    "echidna": "An egg-laying spiny mammal native to Australia.",
    "eel": "A long, snake-like fish.",
    "eland": "The largest of all African antelopes.",
    "elephant": "The largest land animal, featuring a long trunk and tusks.",
    "elk": "A very large species of deer found in forests.",
    "emu": "A large, flightless Australian bird that can run very fast.",
    "falcon": "A swift, diving bird of prey.",
    "ferret": "A small, slender domesticated mammal of the weasel family used for hunting.",
    "finch": "A small seed-eating songbird with a stout bill.",
    "fish": "An aquatic, gill-breathing vertebrate animal.",
    "flamingo": "A tall pink wading bird known for standing on one leg.",
    "fly": "A small winged insect with two wings.",
    "fox": "A clever, bushy-tailed canine known for cunning.",
    "frog": "A tailless amphibian that leaps and croaks near water.",
    "gaur": "The world's largest wild bovine, found in South Asia.",
    "gazelle": "A swift, graceful small antelope of African and Asian grasslands.",
    "gerbil": "A small, desert-dwelling rodent often kept as a pet.",
    "giraffe": "The tallest land animal, famous for its exceptionally long neck.",
    "gnat": "A tiny, annoying biting or non-biting flying insect.",
    "gnu": "Also known as a wildebeest; a large horned African antelope.",
    "goat": "A hardy horned farm animal known for climbing and milk production.",
    "goldfinch": "A brightly colored yellow and black seed-eating songbird.",
    "goldfish": "A popular small golden freshwater aquarium fish.",
    "goose": "A large waterfowl related to ducks and swans.",
    "gorilla": "The largest living primate, powerful and intelligent.",
    "goshawk": "A large, powerful forest-dwelling hawk.",
    "grasshopper": "A plant-eating insect famous for powerful leaps.",
    "grouse": "A plump game bird found in woods and moors.",
    "guanaco": "A wild South American relative of the llama.",
    "gull": "A common coastal seabird with gray and white plumage.",
    "hamster": "A small solitary rodent with cheek pouches for storing food.",
    "hare": "A swift, long-eared mammal similar to, but larger than, a rabbit.",
    "hawk": "A keen-eyed diurnal bird of prey.",
    "hedgehog": "A small nocturnal mammal covered in protective spines.",
    "heron": "A long-legged wetland wading bird that hunts fish.",
    "herring": "A schooling silvery food fish of northern waters.",
    "hippopotamus": "A massive, semi-aquatic African herbivore with a huge mouth.",
    "hornet": "A large, potentially aggressive stinging wasp.",
    "horse": "A large domesticated hoofed animal used for riding and work.",
    "human": "A bipedal primate with high intelligence and complex language.",
    "hummingbird": "A tiny bird capable of hovering and flying backward.",
    "hyena": "A carnivorous African mammal known for its eerie laughing vocalization.",
    "ibex": "A wild mountain goat with massive, ridged horns.",
    "ibis": "A wading bird with a long, down-curved bill and ancient symbolic status.",
    "jackal": "A slender wild canine of Africa and southern Eurasia.",
    "jaguar": "A powerful spotted feline native to the Americas.",
    "jay": "A noisy, colorful bird belonging to the crow family.",
    "jellyfish": "A gelatinous marine creature with stinging tentacles.",
    "kangaroo": "An iconic Australian marsupial famous for hopping on its hind legs.",
    "kingfisher": "A brightly colored bird that plunges into water to catch fish.",
    "koala": "An arboreal Australian marsupial that feeds almost exclusively on eucalyptus leaves.",
    "kookabura": "An Australian bird famous for its call that sounds like human laughter.",
    "kouprey": "A rare, wild forest ox found in Southeast Asia.",
    "kudu": "A large African antelope with magnificent spiral horns.",
    "lapwing": "A crested plover bird known for its erratic flight patterns.",
    "lark": "A ground-dwelling songbird known for singing while flying upward.",
    "lemur": "A primitive primate found only on the island of Madagascar.",
    "leopard": "A stealthy, spotted big cat known for climbing trees.",
    "lion": "The majestic 'king of the jungle' big cat living in social prides.",
    "llama": "A domesticated South American pack animal with thick wool.",
    "lobster": "A large marine crustacean with large claws and a prized tail.",
    "locust": "A type of grasshopper that forms destructive swarms.",
    "loris": "A small, nocturnal primate with huge, round eyes.",
    "louse": "A small, wingless parasitic insect.",
    "lyrebird": "An Australian bird famous for its incredible ability to mimic sounds.",
    "magpie": "A black-and-white bird of the crow family known for collecting shiny objects.",
    "mallard": "A common wild duck with a distinctive glossy green head on males.",
    "manatee": "A gentle, slow-moving aquatic marine mammal also called a sea cow.",
    "mandrill": "A colorful Old World monkey with bright blue and red facial markings.",
    "mantis": "A predatory insect that waits motionlessly with folded front legs.",
    "marten": "A slender, agile tree-dwelling predator of the weasel family.",
    "meerkat": "A small social mongoose that stands upright to watch for predators.",
    "mink": "A semi-aquatic carnivorous mammal raised for its luxurious fur.",
    "mole": "A small burrowing mammal that spends its life underground.",
    "mongoose": "A small agile predator famous for its immunity to snake venom.",
    "monkey": "An agile, tree-dwelling primate with a tail.",
    "moose": "The largest member of the deer family, featuring massive palmate antlers.",
    "mosquito": "A blood-sucking flying pest that can transmit diseases.",
    "mouse": "A tiny rodent with large ears and a long tail.",
    "mule": "The sterile hybrid offspring of a male donkey and a female horse.",
    "narwhal": "An arctic whale famous for its long, spiral unicorn-like tusk.",
    "newt": "A small semi-aquatic salamander.",
    "nightingale": "A small brown thrush renowned for its beautiful nighttime song.",
    "octopus": "A highly intelligent marine mollusk with eight flexible arms.",
    "okapi": "A rare forest-dwelling relative of the giraffe with zebra-like leg stripes.",
    "opossum": "A nocturnal marsupial famous for playing dead when threatened.",
    "oryx": "A large desert antelope with long, straight horns.",
    "ostrich": "The world's largest living bird; flightless and fast-running.",
    "otter": "A playful, semi-aquatic carnivorous mammal.",
    "owl": "A silent-flying nocturnal bird of prey with forward-facing eyes.",
    "ox": "A trained bovine draft animal used for heavy pulling.",
    "oyster": "A marine bivalve mollusk famous for producing pearls.",
    "panda": "A beloved black-and-white bamboo-eating bear native to China.",
    "panther": "A large black feline (a leopard or jaguar with a dark color mutation).",
    "parrot": "A colorful tropical bird capable of mimicking human speech.",
    "partridge": "A plump-bodied game bird native to the Old World.",
    "peafowl": "A large bird where the male sports a stunning fan-like train of feathers.",
    "pelican": "A large water bird with a massive throat pouch used for catching fish.",
    "penguin": "A flightless seabird built for swimming in cold southern oceans.",
    "pheasant": "A game bird where males have brilliant, colorful plumage.",
    "pig": "An intelligent, stocky farm animal kept for meat.",
    "pigeon": "A stout-bodied bird common in cities and towns.",
    "polar-bear": "A massive white arctic bear adapted for hunting seals on ice.",
    "pony": "A small breed of horse.",
    "porcupine": "A rodent heavily covered in sharp, defensive quills.",
    "porpoise": "A small, blunt-snouted relative of the dolphin.",
    "quail": "A small, ground-dwelling game bird.",
    "quelea": "A small African weaver bird considered the world's most abundant bird.",
    "quetzal": "A brightly colored sacred Central American bird with emerald tail feathers.",
    "rabbit": "A fast-breeding burrowing mammal with long ears.",
    "raccoon": "An intelligent nocturnal mammal known for its mask-like markings and clever paws.",
    "rail": "A secretive wetland bird that slips through dense reeds.",
    "ram": "An adult male sheep equipped with curled horns.",
    "rat": "A medium-sized long-tailed rodent.",
    "raven": "A large, deeply intelligent black bird related to crows.",
    "red-deer": "A large majestic deer species native to Europe and western Asia.",
    "red-panda": "A small, reddish-brown arboreal mammal with a ringed tail.",
    "reindeer": "An arctic deer species where both males and females grow antlers.",
    "rhinoceros": "A massive herbivorous mammal with one or two horns on its snout.",
    "rook": "A gregarious black-feathered bird of the crow family.",
    "salamander": "An amphibian that resembles a lizard but has moist skin.",
    "salmon": "A powerful migratory fish famous for swimming upstream to spawn.",
    "sand-dollar": "A flat, burrowing sea urchin found on sandy ocean floors.",
    "sandpiper": "A small wading bird that scurries back and forth along water edges.",
    "sardine": "A small, oily schooling marine fish.",
    "scorpion": "A venomous arachnid equipped with a stinging tail.",
    "seahorse": "A tiny marine fish with an upright posture and a horse-like head.",
    "seal": "A sleek, flippered marine mammal that spends time on ice and land.",
    "shark": "An apex predatory marine fish with a cartilage skeleton.",
    "sheep": "A wool-bearing farm animal raised for fleece and meat.",
    "shrew": "A tiny, hyperactive shrew-like insectivorous mammal.",
    "skunk": "A small mammal notorious for spraying a foul-smelling liquid defense.",
    "snail": "A slow-moving gastropod mollusk that carries a spiral shell.",
    "snake": "A long, legless carnivorous reptile.",
    "sparrow": "A tiny, common seed-eating brown songbird.",
    "spider": "An eight-legged arachnid that often weaves silk webs.",
    "spoonbill": "A wading bird characterized by a flat, spoon-shaped bill.",
    "squid": "A fast-swimming marine mollusk with ten arms.",
    "squirrel": "An energetic, tree-climbing rodent with a bushy tail.",
    "starling": "A noisy songbird known for gathering in massive, swooping flocks.",
    "stingray": "A flat marine fish equipped with a venomous barbed tail spine.",
    "stoat": "A small, fiercely aggressive carnivorous mammal that turns white in winter.",
    "stork": "A tall wading bird associated with folklore and baby deliveries.",
    "swallow": "A graceful aerial bird with a forked tail that catches insects in flight.",
    "swan": "A large, elegant waterfowl with a long curved neck.",
    "tapir": "A large, primitive forest mammal with a flexible short trunk.",
    "tarsier": "A tiny nocturnal primate with massive eyes and long fingers.",
    "termite": "A social wood-eating insect that builds large mounds.",
    "tiger": "A powerful striped big cat native to Asia.",
    "toad": "An amphibian with dry, warty skin similar to a frog.",
    "trout": "A popular freshwater game and food fish.",
    "turkey": "A large American game bird traditionally eaten at holidays.",
    "turtle": "A reptile encased in a protective bony shell.",
    "viper": "A heavily built venomous snake with hinged fangs.",
    "vulture": "A large scavenging bird of prey that feeds on carrion.",
    "wallaby": "A marsupial similar to a kangaroo, but smaller.",
    "walrus": "A large arctic marine mammal featuring prominent long tusks.",
    "wasp": "A winged stinging insect with a narrow waist.",
    "weasel": "A tiny, slender, and fierce carnivorous predator.",
    "whale": "A massive intelligent marine mammal that breathes air.",
    "wildcat": "A fierce, untamed small feline ancestor of domestic cats.",
    "wolf": "A social, pack-hunting wild canine.",
    "wolverine": "A stocky, notoriously tough and fierce northern predator.",
    "wombat": "A sturdy, burrowing Australian marsupial with cube-shaped droppings.",
    "woodcock": "A heavily camouflaged forest-dwelling game bird.",
    "woodpecker": "A bird specialized in hammering tree trunks with its bill for insects.",
    "worm": "A soft-bodied tube-like invertebrate.",
    "wren": "A tiny, active brown songbird with an upright tail.",
    "yak": "A shaggy, heavy-coated wild ox native to the Himalayas.",
    "zebra": "An iconic African wild horse marked with black-and-white stripes."
}